package com.epam.service;

import com.epam.entity.Review;
import com.epam.entity.enums.Appraisal;
import com.epam.exception.ServiceException;

import java.util.List;
import java.util.Optional;

public interface ReviewService extends BaseService<Review> {
    /**
     * Finds all reviews related to the film
     *
     * @throws ServiceException if {@code DaoException} occurs (database access error)
     */
    List<Review> findAllByMovieId(Integer id) throws ServiceException;

    List<Review> findAllByUserId(Integer id) throws ServiceException;

    /**
     * Creates and returns autogenerated (@code Review) id
     *
     * @param text      a review content
     * @param appraisal the number of stars set
     * @return (@ code true) If this is the first user comment on this movie
     * @throws ServiceException if {@code DaoException} occurs (database access error)
     */
    boolean create(String text, Appraisal appraisal, Integer movieId, Integer userId) throws ServiceException;

    /**
     * Returns user feedback to the movie with (@param movie_id)
     *
     * @return (@ code true) If this is the first user comment on this movie
     * @throws ServiceException if {@code DaoException} occurs (database access error)
     */
    Optional<Review> findByMovieIdUserId(Integer movieId, Integer userId) throws ServiceException;

    Double getAverageRating(Integer movieId) throws ServiceException;

    boolean deleteByMovieIdUserId(Integer movieId, Integer userId) throws ServiceException;
}
